// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SMD_Solder_v0.0.1

#include "../ui.h"

// COMPONENT Panel1

lv_obj_t * ui_Panel1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Panel1;
    cui_Panel1 = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_Panel1, 100);
    lv_obj_set_height(cui_Panel1, 50);
    lv_obj_set_x(cui_Panel1, -4);
    lv_obj_set_y(cui_Panel1, -38);
    lv_obj_set_align(cui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(cui_Panel1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_PANEL1_NUM);
    children[UI_COMP_PANEL1_PANEL1] = cui_Panel1;
    lv_obj_add_event_cb(cui_Panel1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Panel1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Panel1_create_hook(cui_Panel1);
    return cui_Panel1;
}

