// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SMD_Solder_v0.0.1

#ifndef _UI_COMP_PANEL1_H
#define _UI_COMP_PANEL1_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Panel1
#define UI_COMP_PANEL1_PANEL1 0
#define _UI_COMP_PANEL1_NUM 1
lv_obj_t * ui_Panel1_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
