// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SMD_Solder_v0.0.1

#ifndef UI_SCSOLDER_H
#define UI_SCSOLDER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SCSolder
extern void ui_SCSolder_screen_init(void);
extern void ui_SCSolder_screen_destroy(void);
extern lv_obj_t * ui_SCSolder;
extern void ui_event_BHome2(lv_event_t * e);
extern lv_obj_t * ui_BHome2;
extern lv_obj_t * ui_TStatus;
extern lv_obj_t * ui_ValTemp3;
extern lv_obj_t * ui_Chart3;
extern lv_obj_t * ui_Chart3_Xaxis;
extern lv_obj_t * ui_Chart3_Yaxis1;
extern lv_obj_t * ui_Chart3_Yaxis2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_BHome2;
extern lv_obj_t * uic_TStatus;
extern lv_obj_t * uic_ValTemp3;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

