// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SMD_Solder_v0.0.1

#ifndef UI_SCSETTINGS_H
#define UI_SCSETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SCSettings
extern void ui_SCSettings_screen_init(void);
extern void ui_SCSettings_screen_destroy(void);
extern lv_obj_t * ui_SCSettings;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Chart1_Xaxis;
extern lv_obj_t * ui_Chart1_Yaxis1;
extern lv_obj_t * ui_Chart1_Yaxis2;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label10;
extern void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

