// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SMD_Solder_v0.0.1

#ifndef UI_SCHOME_H
#define UI_SCHOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SCHome
extern void ui_SCHome_screen_init(void);
extern void ui_SCHome_screen_destroy(void);
extern lv_obj_t * ui_SCHome;
extern void ui_event_BSetTemperature(lv_event_t * e);
extern lv_obj_t * ui_BSetTemperature;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_ValTemp1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ValTemp;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

