// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Temp_disp

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_varTemp;
extern lv_obj_t * ui_Temp;
extern lv_obj_t * ui_LeftArrow;
// CUSTOM VARIABLES
extern lv_obj_t * uic_varTemp;
extern lv_obj_t * uic_Temp;
extern lv_obj_t * uic_LeftArrow;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

