// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SMD_Solder_v0.0.1

#include "../ui.h"

lv_obj_t * uic_ValTemp;
lv_obj_t * ui_SCHome = NULL;
lv_obj_t * ui_BSetTemperature = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_ValTemp1 = NULL;
// event funtions
void ui_event_BSetTemperature(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_SCSolder, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SCSolder_screen_init);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_SCSetTemp, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SCSetTemp_screen_init);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_SCSettings, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SCSettings_screen_init);
    }
}

// build funtions

void ui_SCHome_screen_init(void)
{
    ui_SCHome = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SCHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_SCHome, &ui_img_bk_dark_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BSetTemperature = lv_button_create(ui_SCHome);
    lv_obj_set_width(ui_BSetTemperature, 126);
    lv_obj_set_height(ui_BSetTemperature, 34);
    lv_obj_set_x(ui_BSetTemperature, 3);
    lv_obj_set_y(ui_BSetTemperature, -15);
    lv_obj_set_align(ui_BSetTemperature, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BSetTemperature, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BSetTemperature, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BSetTemperature, 44, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BSetTemperature, lv_color_hex(0x253A24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BSetTemperature, 190, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_button_create(ui_SCHome);
    lv_obj_set_width(ui_Button3, 126);
    lv_obj_set_height(ui_Button3, 34);
    lv_obj_set_x(ui_Button3, 2);
    lv_obj_set_y(ui_Button3, 39);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button3, 44, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x253A24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 190, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_button_create(ui_SCHome);
    lv_obj_set_width(ui_Button4, 126);
    lv_obj_set_height(ui_Button4, 34);
    lv_obj_set_x(ui_Button4, 3);
    lv_obj_set_y(ui_Button4, 98);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button4, 44, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x253A24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 190, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_SCHome);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 4);
    lv_obj_set_y(ui_Label6, -16);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Solder");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x2FAB3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_SCHome);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 3);
    lv_obj_set_y(ui_Label2, 96);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Settings");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x2FAB3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_SCHome);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 1);
    lv_obj_set_y(ui_Label3, 39);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Set Temp");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x2FAB3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ValTemp1 = lv_label_create(ui_SCHome);
    lv_obj_set_width(ui_ValTemp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ValTemp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ValTemp1, 2);
    lv_obj_set_y(ui_ValTemp1, -88);
    lv_obj_set_align(ui_ValTemp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ValTemp1, "25 °C");
    lv_obj_set_style_text_color(ui_ValTemp1, lv_color_hex(0x29CE20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ValTemp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ValTemp1, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ValTemp1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ValTemp1, lv_color_hex(0x3AB634), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ValTemp1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ValTemp1, lv_color_hex(0x179130), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ValTemp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ValTemp1, 75, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ValTemp1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BSetTemperature, ui_event_BSetTemperature, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    uic_ValTemp = ui_ValTemp1;

}

void ui_SCHome_screen_destroy(void)
{
    if(ui_SCHome) lv_obj_del(ui_SCHome);

    // NULL screen variables
    ui_SCHome = NULL;
    ui_BSetTemperature = NULL;
    ui_Button3 = NULL;
    ui_Button4 = NULL;
    ui_Label6 = NULL;
    ui_Label2 = NULL;
    ui_Label3 = NULL;
    uic_ValTemp = NULL;
    ui_ValTemp1 = NULL;

}
