// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SMD_Solder_v0.0.1

#include "../ui.h"

lv_obj_t * ui_SCLolos = NULL;
lv_obj_t * ui_LolosFactory = NULL;
lv_obj_t * ui_Charging = NULL;
lv_obj_t * ui_Label5 = NULL;
// event funtions
void ui_event_SCLolos(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_SCHome, LV_SCR_LOAD_ANIM_FADE_OUT, 300, 3000, &ui_SCHome_screen_init);
    }
}

// build funtions

void ui_SCLolos_screen_init(void)
{
    ui_SCLolos = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SCLolos, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_SCLolos, &ui_img_bk_dark_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LolosFactory = lv_label_create(ui_SCLolos);
    lv_obj_set_width(ui_LolosFactory, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LolosFactory, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LolosFactory, 2);
    lv_obj_set_y(ui_LolosFactory, -38);
    lv_obj_set_align(ui_LolosFactory, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LolosFactory, "LolosFactory");
    lv_obj_set_style_text_color(ui_LolosFactory, lv_color_hex(0x29CF20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LolosFactory, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LolosFactory, &ui_font_LolosFactoryFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Charging = lv_bar_create(ui_SCLolos);
    lv_bar_set_value(ui_Charging, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Charging, 5, LV_ANIM_OFF);
    lv_obj_set_width(ui_Charging, 179);
    lv_obj_set_height(ui_Charging, 8);
    lv_obj_set_x(ui_Charging, 1);
    lv_obj_set_y(ui_Charging, 82);
    lv_obj_set_align(ui_Charging, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Charging, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Charging, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Charging, lv_color_hex(0x055413), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Charging, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Charging, lv_color_hex(0x07740E), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Charging, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Charging, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Charging, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Charging, lv_color_hex(0x104005), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Charging, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Charging, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Charging, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Charging, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Charging,
                                                                                               lv_obj_get_style_pad_right(ui_Charging, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Label5 = lv_label_create(ui_SCLolos);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 1);
    lv_obj_set_y(ui_Label5, 0);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "SMD Solder");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x29CE20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SCLolos, ui_event_SCLolos, LV_EVENT_ALL, NULL);

}

void ui_SCLolos_screen_destroy(void)
{
    if(ui_SCLolos) lv_obj_del(ui_SCLolos);

    // NULL screen variables
    ui_SCLolos = NULL;
    ui_LolosFactory = NULL;
    ui_Charging = NULL;
    ui_Label5 = NULL;

}
