// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SMD_Solder_v0.0.1

#ifndef UI_SCSETTEMP_H
#define UI_SCSETTEMP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SCSetTemp
extern void ui_SCSetTemp_screen_init(void);
extern void ui_SCSetTemp_screen_destroy(void);
extern lv_obj_t * ui_SCSetTemp;
extern lv_obj_t * ui_ValTemp2;
extern void ui_event_BLesTemp(lv_event_t * e);
extern lv_obj_t * ui_BLesTemp;
extern void ui_event_BHeat(lv_event_t * e);
extern lv_obj_t * ui_BHeat;
extern lv_obj_t * ui_THeat;
extern void ui_event_BMorTemp(lv_event_t * e);
extern lv_obj_t * ui_BMorTemp;
extern void ui_event_BHome1(lv_event_t * e);
extern lv_obj_t * ui_BHome1;
extern lv_obj_t * ui_ValActualTemp;
extern lv_obj_t * ui_TDesired;
extern lv_obj_t * ui_TReal;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ValTemp2;
extern lv_obj_t * uic_BLesTemp;
extern lv_obj_t * uic_BHeat;
extern lv_obj_t * uic_THeat;
extern lv_obj_t * uic_BMorTemp;
extern lv_obj_t * uic_BHome1;
extern lv_obj_t * uic_ValActualTemp;
extern lv_obj_t * uic_TReal;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

