// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SMD_Solder_v0.0.1

#ifndef UI_SCHOME_H
#define UI_SCHOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SCHome
extern void ui_SCHome_screen_init(void);
extern void ui_SCHome_screen_destroy(void);
extern lv_obj_t * ui_SCHome;
extern void ui_event_BSolder(lv_event_t * e);
extern lv_obj_t * ui_BSolder;
extern lv_obj_t * ui_TextSolder;
extern void ui_event_BSetTemp(lv_event_t * e);
extern lv_obj_t * ui_BSetTemp;
extern lv_obj_t * ui_TSetTemp;
extern void ui_event_BSettings(lv_event_t * e);
extern lv_obj_t * ui_BSettings;
extern lv_obj_t * ui_TSettings;
extern lv_obj_t * ui_ValTemp1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_BSetTemp;
extern lv_obj_t * uic_TSetTemp;
extern lv_obj_t * uic_BSettings;
extern lv_obj_t * uic_TSettings;
extern lv_obj_t * uic_ValTemp;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

