// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SMD_Solder_v0.0.1

#include "../ui.h"

lv_obj_t * ui_SCSolder = NULL;
lv_obj_t * ui_Button10 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Chart3 = NULL;
lv_obj_t * ui_Chart3_Xaxis = NULL;
lv_obj_t * ui_Chart3_Yaxis1 = NULL;
lv_obj_t * ui_Chart3_Yaxis2 = NULL;
// event funtions
void ui_event_Button10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_SCHome, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SCHome_screen_init);
    }
}

// build funtions

void ui_SCSolder_screen_init(void)
{
    ui_SCSolder = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SCSolder, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_SCSolder, &ui_img_bk_dark_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button10 = lv_button_create(ui_SCSolder);
    lv_obj_set_width(ui_Button10, 42);
    lv_obj_set_height(ui_Button10, 43);
    lv_obj_set_x(ui_Button10, 86);
    lv_obj_set_y(ui_Button10, -134);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button10, 44, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button10, lv_color_hex(0x253A24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button10, 190, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Button10, &ui_img_home3_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_SCSolder);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -1);
    lv_obj_set_y(ui_Label11, -29);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Status : Soldering");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x29CE20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_SCSolder);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 1);
    lv_obj_set_y(ui_Label12, -83);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "25 °C");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x29CE20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label12, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label12, lv_color_hex(0x3AB634), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label12, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Label12, lv_color_hex(0x179130), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Label12, 75, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Label12, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart3 = lv_chart_create(ui_SCSolder);
    lv_obj_set_width(ui_Chart3, 172);
    lv_obj_set_height(ui_Chart3, 100);
    lv_obj_set_x(ui_Chart3, -1);
    lv_obj_set_y(ui_Chart3, 71);
    lv_obj_set_align(ui_Chart3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Chart3, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_Chart3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_Chart3, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_Chart3, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_Chart3, LV_CHART_TYPE_LINE);

    ui_Chart3_Xaxis = lv_scale_create(ui_Chart3);
    lv_scale_set_mode(ui_Chart3_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_Chart3_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_Chart3_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_Chart3_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_Chart3,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart3, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_Chart3_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart3_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_Chart3_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart3_Xaxis, 5, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_Chart3_Xaxis, 10, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_Chart3_Xaxis, 0, 5 > 0 ? 5 - 1 : 0);
    lv_scale_set_total_tick_count(ui_Chart3_Xaxis, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart3_Xaxis, 2 >= 1 ? 2 : 1);
    ui_Chart3_Yaxis1 = lv_scale_create(ui_Chart3);
    lv_scale_set_mode(ui_Chart3_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_Chart3_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_Chart3_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_Chart3_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_Chart3,
                                                                   LV_PART_MAIN) - lv_obj_get_style_border_width(ui_Chart3, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_Chart3_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart3_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart3_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart3_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart3_Yaxis1, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_Chart3_Yaxis1, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart3_Yaxis1, 2 >= 1 ? 2 : 1);
    ui_Chart3_Yaxis2 = lv_scale_create(ui_Chart3);
    lv_scale_set_mode(ui_Chart3_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_Chart3_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_Chart3_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_Chart3_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_Chart3,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart3, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_Chart3_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart3_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart3_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart3_Yaxis2, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart3_Yaxis2, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_Chart3_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart3_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_chart_series_t * ui_Chart3_series_1 = lv_chart_add_series(ui_Chart3, lv_color_hex(0x808080),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart3_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart3, ui_Chart3_series_1, ui_Chart3_series_1_array);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_Chart3, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_Chart3, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);

}

void ui_SCSolder_screen_destroy(void)
{
    if(ui_SCSolder) lv_obj_del(ui_SCSolder);

    // NULL screen variables
    ui_SCSolder = NULL;
    ui_Button10 = NULL;
    ui_Label11 = NULL;
    ui_Label12 = NULL;
    ui_Chart3 = NULL;

}
