// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SMD_Solder_v0.0.1

#ifndef UI_SCLOLOS_H
#define UI_SCLOLOS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SCLolos
extern void ui_SCLolos_screen_init(void);
extern void ui_SCLolos_screen_destroy(void);
extern void ui_event_SCLolos(lv_event_t * e);
extern lv_obj_t * ui_SCLolos;
extern lv_obj_t * ui_LolosFactory;
extern lv_obj_t * ui_Charging;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

