// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Temp_disp

#include "../ui.h"

lv_obj_t * uic_LeftArrow;
lv_obj_t * uic_Temp;
lv_obj_t * uic_varTemp;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_varTemp = NULL;
lv_obj_t * ui_Temp = NULL;
lv_obj_t * ui_LeftArrow = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Screen1, &ui_img_bakground_blue_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image2, &ui_img_icon_gold_png);
    lv_obj_set_width(ui_Image2, 77);
    lv_obj_set_height(ui_Image2, 25);
    lv_obj_set_x(ui_Image2, 62);
    lv_obj_set_y(ui_Image2, -132);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_varTemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_varTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_varTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_varTemp, 0);
    lv_obj_set_y(ui_varTemp, 3);
    lv_obj_set_align(ui_varTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_varTemp, "0 °C");
    lv_obj_set_style_text_color(ui_varTemp, lv_color_hex(0xA08203), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_varTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_varTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_varTemp, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_varTemp, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_Temp, 140);
    lv_obj_set_height(ui_Temp, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Temp, 0);
    lv_obj_set_y(ui_Temp, -67);
    lv_obj_set_align(ui_Temp, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_Temp, "Temperature");
    lv_textarea_set_placeholder_text(ui_Temp, "Placeholder...");
    lv_textarea_set_one_line(ui_Temp, true);
    lv_obj_set_style_text_color(ui_Temp, lv_color_hex(0xECA73E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Temp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temp, &ui_font_Roboto2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Temp, lv_color_hex(0xC81717), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Temp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LeftArrow = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_LeftArrow, 48);
    lv_obj_set_height(ui_LeftArrow, 45);
    lv_obj_set_x(ui_LeftArrow, 3);
    lv_obj_set_y(ui_LeftArrow, 88);
    lv_obj_set_align(ui_LeftArrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LeftArrow, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_LeftArrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_LeftArrow, &ui_img_left_arrow_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_LeftArrow, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_LeftArrow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_LeftArrow, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_LeftArrow, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_varTemp = ui_varTemp;
    uic_Temp = ui_Temp;
    uic_LeftArrow = ui_LeftArrow;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Image2 = NULL;
    uic_varTemp = NULL;
    ui_varTemp = NULL;
    uic_Temp = NULL;
    ui_Temp = NULL;
    uic_LeftArrow = NULL;
    ui_LeftArrow = NULL;

}
