// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SMD_Solder_v0.0.1

#ifndef UI_SCSETTEMP_H
#define UI_SCSETTEMP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SCSetTemp
extern void ui_SCSetTemp_screen_init(void);
extern void ui_SCSetTemp_screen_destroy(void);
extern lv_obj_t * ui_SCSetTemp;
extern lv_obj_t * ui_ValTemp2;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label9;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

