// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SMD_Solder_v0.0.1

#ifndef UI_TFUNCTION_H
#define UI_TFUNCTION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TFunction
extern void ui_TFunction_screen_init(void);
extern void ui_TFunction_screen_destroy(void);
extern lv_obj_t * ui_TFunction;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Chart1_Xaxis;
extern lv_obj_t * ui_Chart1_Yaxis1;
extern lv_obj_t * ui_Chart1_Yaxis2;
extern lv_obj_t * ui_ValTemp4;
extern lv_obj_t * ui_Label10;
extern void ui_event_BHome3(lv_event_t * e);
extern lv_obj_t * ui_BHome3;
// CUSTOM VARIABLES
extern lv_obj_t * uic_TFunction;
extern lv_obj_t * uic_BHome3;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

