// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SMD_Solder_v0.0.1

#ifndef _SMD_SOLDER_V0_0_1_UI_H
#define _SMD_SOLDER_V0_0_1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "Display_Manager.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_SCLolos.h"
#include "screens/ui_SCHome.h"
#include "screens/ui_SCSolder.h"
#include "screens/ui_TFunction.h"
#include "screens/ui_SCSetTemp.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bk_dark_png);    // assets/Bk_dark.png
LV_IMG_DECLARE(ui_img_home3_png);    // assets/Home3.png

// FONTS
LV_FONT_DECLARE(ui_font_LolosFactoryFont24);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
