// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Temp_disp

#ifndef _TEMP_DISP_UI_H
#define _TEMP_DISP_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bakground_blue_png);    // assets/Bakground_blue.png
LV_IMG_DECLARE(ui_img_icon_gold_png);    // assets/Icon_gold.png
LV_IMG_DECLARE(ui_img_left_arrow_png);    // assets/Left_arrow.png

// FONTS
LV_FONT_DECLARE(ui_font_Roboto2);
LV_FONT_DECLARE(ui_font_Roboto1);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
