// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SMD_Solder_v0.0.1

#include "ui.h"

void BSolder_Cliked(lv_event_t * e)
{
	// Your code here
	ScreenButtonClicked(DISPLAY_MANAGER_BUTTON_Solder);
}

void BSetTempCliked(lv_event_t * e)
{
	// Your code here
	ScreenButtonClicked(DISPLAY_MANAGER_BUTTON_SetTemp);
}

void BSettings_Cliked(lv_event_t * e)
{
	// Your code here
	ScreenButtonClicked(DISPLAY_MANAGER_BUTTON_Settings);
}

void InecreaseTemp(lv_event_t * e)
{
	// Your code here
	ScreenButtonClicked(DISPLAY_MANAGER_BUTTON_MoreTemp);
}

void Heat(lv_event_t * e)
{
	// Your code here
	ScreenButtonClicked(DISPLAY_MANAGER_BUTTON_Heat);
}

void DecreaseTemp(lv_event_t * e)
{
	// Your code here
	ScreenButtonClicked(DISPLAY_MANAGER_BUTTON_LessTemp);
}
