// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SMD_Solder_v0.0.1

#include "ui.h"

void InecreaseTemp(lv_event_t * e)
{
	// Your code here
}

void Heat(lv_event_t * e)
{
	// Your code here
}

void DecreaseTemp(lv_event_t * e)
{
	// Your code here
}
